global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@example.com'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'admin-emails'
  routes:
    - match:
        severity: critical
      receiver: 'admin-emails'
      continue: true

    - match:
        severity: warning
      receiver: 'admin-emails'
      continue: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
  - name: 'admin-emails'
    email_configs:
      - to: '${ADMIN_EMAIL}'
        send_resolved: true
        html: |
          {{ if .Alerts.Firing -}}
          <h3>🔥 Активные оповещения</h3>
          <table>
            <tr><th>Название</th><th>Сервис</th><th>Описание</th><th>Значение</th><th>Начало</th></tr>
            {{- range .Alerts.Firing }}
            <tr>
              <td>{{ .Labels.alertname }}</td>
              <td>{{ .Labels.job }}</td>
              <td>{{ .Annotations.description }}</td>
              <td>{{ .Annotations.value }}</td>
              <td>{{ .StartsAt.Format "02.01.2006 15:04:05" }}</td>
            </tr>
            {{- end }}
          </table>
          {{- end }}
          
          {{ if .Alerts.Resolved -}}
          <h3>✅ Разрешенные оповещения</h3>
          <table>
            <tr><th>Название</th><th>Сервис</th><th>Описание</th><th>Значение</th><th>Закрыто</th></tr>
            {{- range .Alerts.Resolved }}
            <tr>
              <td>{{ .Labels.alertname }}</td>
              <td>{{ .Labels.job }}</td>
              <td>{{ .Annotations.description }}</td>
              <td>{{ .Annotations.value }}</td>
              <td>{{ .EndsAt.Format "02.01.2006 15:04:05" }}</td>
            </tr>
            {{- end }}
          </table>
          {{- end }}